try {
  throw new Error("test");
} catch (e) {
  console.error(e);
}
